name: 新功能请求
description: 针对于框架提出新功能请求
title: "[Feat]: "
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        ## 感谢您愿意向 LiteLoaderQQNT 框架请求新功能
        ## 以下是一些注意事项，请务必阅读让我们能够更容易处理

        ### ❗ | 确定没有类似/一致的 Feature 已在当前 Commit/PR 中被提出或实现。
        ### 如果您不知道如何有效、精准地表述，我们建议您先阅读[《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way)，另有英文原文可供参考: [How to Ask Questions the Smart Way](http://www.catb.org/~esr/faqs/smart-questions.html)

        ---
  - type: checkboxes
    id: terms
    attributes:
      label: 请确保您已阅读以上注意事项，并勾选下方的确认框。
      options:
        - label: 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。
          required: true
        - label: 我确定这是一个从未被提出和实现过的功能 (请阅读以下两则)。
          required: true
        - label: 我已在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要请求的功能，没有找到类似 Issue。
          required: true
        - label: 我已在 [Pull Request](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/pulls) 中找过我要请求的功能，没有找到类似 Pull Request。
          required: true
        - label: 我已知晓并同意，此模板仅用于向 LiteLoaderQQNT 框架请求新功能，否则我的 Issue 可能会被无条件关闭/锁定。
          required: true


  - type: textarea
    id: feature-request
    attributes:
      label: 需要添加的功能内容
      description: |
        请具体提出想添加的功能，包括实现的模拟（如有）
        是否有类似的功能已经实现？如有请肯定地提出与该功能不同的地方/想改进/添加该功能的哪一部分。
    validations:
      required: true
